# Generated by Django 5.2.7 on 2025-10-02 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entrance",
            fields=[
                (
                    "id",
                    models.SmallIntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="files/", verbose_name="Archivo")),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total",
                    models.IntegerField(blank=True, null=True, verbose_name="Total"),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "entrance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people_counter.entrance",
                        verbose_name="Entrada",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField(verbose_name="Hora")),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people_counter.report",
                        verbose_name="Reporte",
                    ),
                ),
            ],
        ),
    ]
