# Generated by Django 5.2.7 on 2025-10-03 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people_counter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Fecha"
            ),
            preserve_default=False,
        ),
    ]
