# Generated by Django 5.2.7 on 2025-10-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people_counter", "0002_file_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportdetail",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Cantidad"),
            preserve_default=False,
        ),
    ]
