# Generated by Django 5.2.7 on 2025-10-03 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people_counter", "0003_reportdetail_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="date",
        ),
    ]
