# Generated by Django 5.2.7 on 2025-10-03 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people_counter", "0004_remove_file_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="people_counter.file",
                verbose_name="Archivo",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="entrance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="people_counter.entrance",
                verbose_name="Entrada",
            ),
        ),
        migrations.AlterField(
            model_name="reportdetail",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reportdetails",
                to="people_counter.report",
                verbose_name="Reporte",
            ),
        ),
    ]
