# Generated by Django 5.2.7 on 2025-10-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people_counter", "0005_report_file_alter_report_entrance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="direction",
            field=models.CharField(
                choices=[("entran", "Entrada"), ("salen", "Salida")],
                default="entran",
                max_length=6,
                verbose_name="Dirección",
            ),
            preserve_default=False,
        ),
    ]
