# Generated by Django 5.2.7 on 2025-10-05 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people_counter', '0006_report_direction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('date', 'direction', 'entrance')},
        ),
    ]
